{{- if and .Values.recommendationApi.enabled .Values.recommendationApi.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "recsys.fullname" . }}-recommendation-api
  labels:
    {{- include "recsys.serviceLabels" (dict "Release" .Release "Chart" .Chart "serviceName" "recommendation-api") | nindent 4 }}
spec:
  minAvailable: {{ .Values.recommendationApi.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "recsys.selectorLabels" (dict "Release" .Release "serviceName" "recommendation-api") | nindent 6 }}
{{- end }}
